# Generated by Django 4.2.11 on 2024-04-26 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='ngn_id',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500)),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='usd_id',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500)),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('ngn_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500))),
                ('usd_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500))),
                ('date_created', models.DateField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payoutLink',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('buyer_currency', models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD')], max_length=20)),
                ('buyer_amount', models.FloatField(default=0)),
                ('seller_currency', models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD')], max_length=20)),
                ('seller_amount', models.FloatField(default=0)),
                ('seller_email', models.EmailField(blank=True, max_length=254)),
                ('seller_username', models.CharField(blank=True, max_length=100)),
                ('buyer_approved', models.BooleanField(default=False)),
                ('seller_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Approved', 'Approved')], default='Pending', max_length=100)),
                ('is_done', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
