# Generated by Django 4.2.11 on 2024-04-13 15:10

from django.db import migrations, models
import django_cryptography.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('person_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200))),
                ('business_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200))),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=50)),
                ('role', models.CharField(help_text='CEO, CFO', max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('dob', models.DateField(default='1900-01-01', verbose_name='Date of Birth')),
                ('zip_code', models.IntegerField(null=True, verbose_name='Zip Code')),
                ('address_line', models.CharField(max_length=200, verbose_name='Address House no and street')),
                ('city', models.CharField(max_length=50, verbose_name='Address City')),
                ('state', models.CharField(max_length=50, verbose_name='Address State')),
                ('country', models.CharField(choices=[('AU', 'Australia'), ('CA', 'Canada'), ('GH', 'Ghana'), ('NG', 'Nigeria'), ('US', 'United States')], max_length=50, verbose_name='Country Codes e.g US, NG')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
