# Generated by Django 4.2.11 on 2024-04-11 20:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.UUIDField(default=uuid.UUID('683f587e-db2b-4991-8234-d9164610f975'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(default=uuid.UUID('c3de8404-1ffb-4c98-a08e-f682d2ffb8df'), editable=False, primary_key=True, serialize=False),
        ),
    ]
